### ISSUE TITLE
Agreement in ad-hd phrases?

### ISSUE THREAD

**Issue by olzama** [delph-in/srg#89]
It would appear the grammar overgenerates in cases like this:

![Screenshot from 2023-11-27 15-49-40](https://github.com/delph-in/srg/assets/10963114/94a6a7c7-68b0-4c54-a6ca-7ad655921d91)

![Screenshot from 2023-11-27 15-41-04](https://github.com/delph-in/srg/assets/10963114/7628446f-bc01-456a-b0f1-ba14192687d6)

I am not sure this is overgeneration because maybe this is just something like "She isn't the evil", or some such thing (cf: "Ella no es poco", as in "She is enough [not little]"? Maybe not. Of course in this case this isn't the intended reading even if such things were possible.

**Comment by suarezallegue** [comment]
I'd say it is overgeneration.

In "Ella no es poco", _poco_ (adv.) and _poco/-a_ (adj.) can be mistaken because they share the same form. In this example, lack of agreement is not a problem assuming that _poco_ is an adverb (if it was intended as an adjective, then it should agree with the pronoun, of course). However, in "Ella no es malo", there is no room for confusion because _mal_ (adv.) and _malo/-a_ (adj.) don't have the same form. Therefore, since the word in the sentence is clearly an adjective, agreement is necessary ("Ella no es mala").

**Comment by olzama** [comment]
I fixed this in the srg-mal version in the GAUSS repository but it remains to be seen what we lose e.g. in the TIBIDABO treebank if we implement this change here. https://github.com/olzama/gauss/commit/5c7d4ead5aa0a0cefc59987dfc16398af2db5f1f
